### ISSUE TITLE
Use of global variables in assignment 1 task3.py

### ISSUE THREAD

**Issue by olaals** [hukkelas/TDT4265-StarterCode#1]
Is it intended to use global variables in line 54, 57 and 59 in task3.py in assignment 1? The global variables are Y_val, X_train and Y_train. It wont make a difference unless imported to another script.

**Comment by hukkelas** [comment]
Nope, not supposed to be global variables. But as you note, it should not make much difference for this assignment.

This is fixed in the starter code for assignment 2! Thanks for noting it!
